/**
 * channel → command 映射表（自 api/index.ts 拆出，纯结构移动）。
 *
 * 职责：Electron 的 `ipcRenderer.invoke(channel, ...args)` 是"位置参数"，
 * Tauri 的 `invoke(command, args)` 是"命名参数对象"。本模块集中维护两张表：
 * `COMMAND_MAP` 把 channel（kebab-case）映射为 command（snake_case），
 * `ARG_NAMES` 按位置给出参数名（camelCase —— Tauri 自动映射到 Rust 的
 * snake_case 形参）。通用 call() 见 api/index.ts。
 */

/** Electron 通道名 → Tauri command 名（snake_case）。 */
export const COMMAND_MAP: Record<string, string> = {
  // 身份
  'root-status': 'root_status',
  'root-init': 'root_init',
  'root-unlock': 'root_unlock',
  'root-lock': 'root_lock',
  'root-list-identities': 'root_list_identities',
  'root-set-active': 'root_set_active',
  'root-recover-mnemonic': 'root_recover_mnemonic',
  'root-recover-backup': 'root_recover_backup',
  'root-backup-payload': 'root_backup_payload',
  'root-reveal-mnemonic': 'root_reveal_mnemonic',
  'root-update-profile': 'root_update_profile',
  'root-sign': 'root_sign',
  'root-derive-domain': 'root_derive_domain',
  'root-mnemonic-check': 'root_mnemonic_check',
  // 文档（plugin.doc* 手写包装，不走通用表）
  // 组织
  'org-list-mine': 'org_list_mine',
  'org-create': 'org_create',
  'org-invite-create': 'org_create_invite',
  'org-invite-accept': 'org_accept_invite',
  'org-send-invite': 'org_send_invite',
  'org-respond-invite': 'org_respond_invite',
  'org-invite-records': 'org_invite_records',
  'org-sync-overview': 'org_sync_overview',
  'org-delete': 'org_delete',
  'org-add-member': 'org_add_member',
  'org-remove-member': 'org_remove_member',
  'org-set-gateways': 'org_set_gateways',
  'org-set-public': 'org_set_public',
  'org-update-info': 'org_update_info',
  'org-update-my-identity': 'org_update_my_identity',
  'org-resolve-address': 'org_resolve_address',
  'org-search-known': 'org_search_known',
  // 通讯录
  'contact-overview': 'contact_overview',
  'contact-update-profile': 'contact_update_profile',
  'contact-set-blocked': 'contact_set_blocked',
  'contact-remove-friend': 'contact_remove_friend',
  'contact-send-request': 'contact_send_request',
  'contact-reply-request': 'contact_reply_request',
  'contact-ask-request': 'contact_ask_request',
  'contact-resolve-request': 'contact_resolve_request',
  'contact-tag-create': 'contact_tag_create',
  'contact-tag-rename': 'contact_tag_rename',
  'contact-tag-delete': 'contact_tag_delete',
  'contact-group-create': 'contact_group_create',
  'contact-group-rename': 'contact_group_rename',
  'contact-group-delete': 'contact_group_delete',
  'contact-group-move': 'contact_group_move',
  'contact-set-group': 'contact_set_group',
  'contact-org-group-create': 'contact_org_group_create',
  'contact-org-group-rename': 'contact_org_group_rename',
  'contact-org-group-delete': 'contact_org_group_delete',
  'contact-org-group-move': 'contact_org_group_move',
  // 消息
  'message-list-conversations': 'message_list_conversations',
  'message-list-messages': 'message_list_messages',
  'message-ensure-direct': 'message_ensure_direct',
  'message-send-text': 'message_send_text',
  'message-resend': 'message_resend',
  'message-recall': 'message_recall',
  'message-delete': 'message_delete',
  'message-mark-read': 'message_mark_read',
  'message-set-draft': 'message_set_draft',
  'message-toggle-pin': 'message_toggle_pin',
  'message-toggle-mute': 'message_toggle_mute',
  'message-clear': 'message_clear',
  'message-delete-conversation': 'message_delete_conversation',
  // 应用消息（服务号模型，p2p-messages.md §20）
  'message-app-send': 'message_app_send',
  'message-app-list': 'message_app_list',
  'message-app-mark-read': 'message_app_mark_read',
  'message-app-delete-conversation': 'message_app_delete_conversation',
  // 数据治理
  'data-usage': 'data_usage',
  'data-cleanup-now': 'data_cleanup_now',
  'data-export': 'data_export',
  'data-purge-preview': 'data_purge_preview',
  'data-purge-execute': 'data_purge_execute',
  // 存证
  'evidence-head-hash': 'evidence_head_hash',
  'evidence-verify': 'evidence_verify',
  // P2P
  'p2p-start': 'p2p_start',
  'p2p-stop': 'p2p_stop',
  'p2p-info': 'p2p_status',
  'p2p-broadcast': 'p2p_broadcast',
  'p2p-clear-peer-records': 'p2p_clear_peer_records',
  'p2p-sync-peer-organizations': 'p2p_sync_peer_organizations',
  'p2p-list-peer-records': 'p2p_list_peer_records',
  'p2p-get-dht-mode': 'p2p_get_dht_mode',
  'p2p-set-dht-mode': 'p2p_set_dht_mode',
  'p2p-make-node-card': 'p2p_make_node_card',
  'p2p-import-node-card': 'p2p_import_node_card',
  // 插件运行时（tab 模式语义，见 api/index.ts 注记）
  'plugin-identity-sign': 'plugin_identity_sign',
  'plugin-identity-verify': 'plugin_identity_verify',
  'plugin-org-sync-now': 'plugin_org_sync_now',
  // 插件市场
  'plugin-market-list': 'plugin_market_list',
  'plugin-market-check-updates': 'plugin_market_check_updates',
  'plugin-market-install': 'plugin_market_install',
  'plugin-market-upgrade': 'plugin_market_upgrade',
  'plugin-market-set-enabled': 'plugin_market_set_enabled',
  'plugin-market-resolve-repo': 'plugin_market_resolve_repo',
  'plugin-market-install-from-repo': 'plugin_market_install_from_repo',
  'plugin-market-announce-publish': 'plugin_market_announce_publish',
  'plugin-market-announce-list': 'plugin_market_announce_list',
  'plugin-market-announce-get': 'plugin_market_announce_get',
  // 系统桥接（未读角标 → dock/任务栏徽标）
  'system-set-badge': 'system_set_badge'
};

/**
 * 各通道的位置参数名（camelCase；Tauri 将其映射到 Rust snake_case 形参）。
 * 缺省为 []（无参通道）。undefined 值会被 JSON 序列化丢弃 → Rust 侧得 None。
 */
export const ARG_NAMES: Record<string, string[]> = {
  'root-init': ['password', 'nickname', 'avatar'],
  'root-unlock': ['password', 'rootId'],
  'root-set-active': ['rootId'],
  'root-recover-mnemonic': ['mnemonic', 'newPassword', 'nickname', 'avatar'],
  'root-recover-backup': ['payload', 'password'],
  'root-reveal-mnemonic': ['password'],
  'root-sign': ['payload'],
  'root-derive-domain': ['domain'],
  'root-mnemonic-check': ['input'],
  'org-create': ['input'],
  'org-invite-create': ['orgId'],
  'org-invite-accept': ['code'],
  'org-send-invite': ['orgId', 'targetRootId', 'targetPeerId', 'targetAddresses', 'targetNickname'],
  'org-respond-invite': ['inviteId', 'accept'],
  'org-invite-records': ['orgId'],
  'org-sync-overview': ['orgId'],
  'org-delete': ['orgId'],
  'org-add-member': ['orgId', 'input'],
  'org-remove-member': ['orgId', 'memberRootId'],
  'org-set-gateways': ['orgId', 'gateways'],
  'org-set-public': ['orgId', 'public', 'displayName'],
  'org-update-info': ['orgId', 'name', 'description', 'avatar'],
  'org-update-my-identity': ['orgId', 'nickname', 'avatar', 'gender', 'region', 'signature', 'usePersonalIdentity'],
  'org-resolve-address': ['orgAddress'],
  'org-search-known': ['keyword'],
  'contact-overview': ['spaceKey'],
  'contact-update-profile': ['spaceKey', 'rootId', 'patch'],
  'contact-set-blocked': ['spaceKey', 'rootId', 'blocked'],
  'contact-remove-friend': ['rootId', 'block'],
  'contact-send-request': ['input'],
  'contact-reply-request': ['requestId', 'text'],
  'contact-ask-request': ['requestId', 'text'],
  'contact-resolve-request': ['requestId', 'accept', 'permission'],
  'contact-tag-create': ['spaceKey', 'id', 'name'],
  'contact-tag-rename': ['spaceKey', 'tagId', 'name'],
  'contact-tag-delete': ['spaceKey', 'tagId'],
  'contact-group-create': ['spaceKey', 'id', 'name'],
  'contact-group-rename': ['spaceKey', 'groupId', 'name'],
  'contact-group-delete': ['spaceKey', 'groupId'],
  'contact-group-move': ['spaceKey', 'groupId', 'toIndex'],
  'contact-set-group': ['spaceKey', 'rootId', 'groupId'],
  'contact-org-group-create': ['spaceKey', 'parentId', 'id', 'name'],
  'contact-org-group-rename': ['spaceKey', 'id', 'name'],
  'contact-org-group-delete': ['spaceKey', 'id'],
  'contact-org-group-move': ['spaceKey', 'id', 'toIndex', 'newParentId'],
  'message-list-conversations': ['spaceKey'],
  'message-list-messages': ['spaceKey', 'convId'],
  'message-ensure-direct': ['spaceKey', 'peerId', 'title'],
  'message-send-text': ['spaceKey', 'convId', 'messageId', 'text', 'quote'],
  'message-resend': ['spaceKey', 'convId', 'messageId'],
  'message-recall': ['spaceKey', 'convId', 'messageId'],
  'message-delete': ['spaceKey', 'convId', 'messageId'],
  'message-mark-read': ['spaceKey', 'convId'],
  'message-set-draft': ['spaceKey', 'convId', 'draft'],
  'message-toggle-pin': ['spaceKey', 'convId'],
  'message-toggle-mute': ['spaceKey', 'convId'],
  'message-clear': ['spaceKey', 'convId'],
  'message-delete-conversation': ['spaceKey', 'convId'],
  'message-app-send': ['spaceKey', 'pluginId', 'payload', 'card'],
  'message-app-list': ['spaceKey', 'pluginId'],
  'message-app-mark-read': ['spaceKey', 'pluginId'],
  'message-app-delete-conversation': ['spaceKey', 'pluginId'],
  'data-export': ['filePath'],
  'data-purge-preview': ['orgId', 'beforeTs'],
  'data-purge-execute': ['orgId', 'beforeTs', 'confirmExported'],
  'p2p-broadcast': ['topic', 'message'],
  'p2p-sync-peer-organizations': ['targetPeer'],
  'p2p-set-dht-mode': ['mode'],
  'p2p-make-node-card': ['orgId'],
  'p2p-import-node-card': ['card'],
  'plugin-identity-sign': ['payload', 'pluginDomain'],
  'plugin-identity-verify': ['payload', 'signature', 'publicKey'],
  'plugin-org-sync-now': ['orgId', 'pluginDomain'],
  'plugin-market-check-updates': ['pluginId'],
  'plugin-market-install': ['pluginId'],
  'plugin-market-upgrade': ['pluginId'],
  'plugin-market-set-enabled': ['pluginId', 'enabled'],
  'plugin-market-resolve-repo': ['id'],
  'plugin-market-install-from-repo': ['id'],
  'plugin-market-announce-publish': ['input'],
  'plugin-market-announce-get': ['id'],
  'system-set-badge': ['count']
};
